[package]
name = "tracevm"
version = "0.1.0"
edition = "2021"

[dependencies]
revm = { version = "9.0.0", default-features = false }
alloy-primitives = "0.7.1"
serde_json = "1.0"
queues = "1.0.2"
alloy-sol-types = "0.7"
